#!/usr/bin/env python

import sys
import os
# FIXME Hard-coded path
sys.path.append("./src/ros_robodk_post_processors/scripts/robodk_postprocessors/")
#sys.path.append(os.path.abspath("/home/victor/code/catkin_workspace/src/ros_robodk_post_processors/scripts/robodk_postprocessors/"))

import actionlib
from Motoman import *
from ros_robodk_post_processors.srv import *
import rospy

def generate_native_code_program(req):
    # FIXME Does not work well if service is called twice!
    robot = RobotPost('Motomantest', 'Motoman robot', 6)
    robot.PROG_COMMENT = "Victor"
    robot.ProgStart(req.program_name)
    robot.ACTIVE_TOOL=0
    robot.USE_RELATIVE_JOB=False
    robot.RunMessage("Program generated by Robot Operating System using RoboDK post processors", True)
    robot.MoveJ(Pose([200, 200, 500, 180, 0, 180]), [-46.18419, -6.77518, -20.54925, 71.38674, 49.58727, -302.54752] )
    #robot.MoveL(Pose([200, 250, 348.734575, 180, 0, -150]), [-41.62707, -8.89064, -30.01809, 60.62329, 49.66749, -258.98418] )
    robot.ProgFinish(req.program_name)

    if len(robot.LOG) > 0:
        mbox('Program generation LOG:\n\n' + robot.LOG)
        # FIXME Handle errors

    program=''
    for line in robot.PROG_LIST[-1]:
        print(line)
        program += line

    if req.save_files:
      robot.ProgSave(progname=req.program_name, folder=req.files_saving_dir)
    return [program]

def service_server():
    rospy.init_node('ros_robodk_post_processors')
    s = rospy.Service('generate_native_code_program', GenerateNativeCodeProgram, generate_native_code_program)
    print("Service %s ready" % s.resolved_name)
    rospy.spin()

if __name__ == '__main__':
    service_server()
